FROM linuxserver/code-server:4.90.3
ENV TZ="Asia/Seoul"
ENV PUID=1000
ENV PGID=1000
ENV DEFAULT_WORKSPACE=/code
ENV PASSWORD=password

# RUN apt-get update && apt-get -y upgrade
# RUN apt-get update

# CMD ["sleep", "3600"]